replicaCount: 2

image:
  repository: ghcr.io/j26423397-byte/hello-k8s
  tag: "20dc92636b14527e50bf7ed6e3ab92f600cd2119"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: web.local

config:
  APP_NAME: advanced-web
  APP_MODE: auto-sync-test
secret:
  DB_PASSWORD: "1234"

pvc:
  enabled: true
  storage: 1Gi
  mountPath: /data

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi